// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartAudioReceive(arg1:string):Promise<boolean>;

export function StartAudioSend(arg1:string):Promise<boolean>;

export function StopAudioReceive():Promise<boolean>;

export function StopAudioSend():Promise<boolean>;
