// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartAudioReceive(arg1) {
  return window['go']['main']['App']['StartAudioReceive'](arg1);
}

export function StartAudioSend(arg1) {
  return window['go']['main']['App']['StartAudioSend'](arg1);
}

export function StopAudioReceive() {
  return window['go']['main']['App']['StopAudioReceive']();
}

export function StopAudioSend() {
  return window['go']['main']['App']['StopAudioSend']();
}
